config/routes.rb
Hci3::Application.routes.draw do
  
  # Verisk Pages
  match 'payment_accuracy' => 'payment_accuracy#home', :as => :home
  match 'claims_editing' => 'payment_accuracy#claim_editing', :as => :claim_editing
  match 'fraud_prevention' => 'payment_accuracy#fraud_prevention', :as => :fraud_prevention
  match 'bill_review' => 'payment_accuracy#bill_review', :as => :bill_review
  match 'about_us' => 'payment_accuracy#about_us', :as => :about_us
  match 'nucleus' => 'payment_accuracy#nucleus', :as => :nucleus
  match 'more_info' => 'payment_accuracy#more_info', :as => :more_info

  # Mail Route Paths
  match 'contacts_mailer' => "contacts#contacts_mailer", :as => :contact_mailer
  
  # Admin Paths
  match "login" => "user_sessions#new", :as => :login
  match "logout" => "user_sessions#destroy", :as => :logout
  match "hci-services" => "users#admin_services", :as => :admin_services
  match "hci-articles" => "users#admin_articles", :as => :admin_articles
  match "hci-events" => "users#admin_events", :as => :admin_events
  match "hci-videos" => "users#admin_videos", :as => :admin_videos
  match "hci-tutorial-videos" => "users#admin_tutorial_videos", :as => :admin_tutorial_videos
  match "hci-documents" => "users#admin_documents", :as => :admin_documents
  match "hci-banners" => "users#admin_banners", :as => :admin_banners
  match "hci-advertisements" => "users#admin_ads", :as => :admin_ads
  match "hci-quotes" => "users#admin_quotes", :as => :admin_quotes
  
  # Custom Named Routes
  match "invite-a-friend" => "landing_pages#invite_friend", :as => :invite_friend
  match "thank-you-for-inviting-a-friend" => "landing_pages#invite_thank_you", :as => :invite_thank_you
  match "upload-issuu" => "issuu_uploads#index", :as => :issuu_upload
  match "healthcare-insight-document" => 'issuu_uploads#show', :as => :issue
  # match "nucleus" => "pages#nucleus", :as => :nucleus
  match "healthcare-insight-markets" => "pages#markets", :as => :markets
  match "healthcare-insight-resources" => "pages#resources", :as => :res
  match "healthcare-insight-press-kit" => "pages#press_kit", :as => :press_kit
  match "contact-healthcare-insight" => "contacts#contact_us", :as => :contact
  match "thank-you" => "contacts#thank_you", :as => :contact_thank_you
  match "health-care-press" => "announcements#index", :as => :press
  match "health-care-resources" => "resources#index", :as => :media
  match "careers" => "pages#careers", :as => :careers
  match "healthcare-insight-partners" => "pages#partner", :as => :partners
  match "healthcare-insight-accreditations" => "pages#accreditations", :as => :accreditations
  match "healthcare-insight-privacy-policy-and-disclaimers" => "pages#privacy_policy", :as => :privacy
  match "healthcare-insight-social-media-links" => "pages#social_media", :as => :social
  match "public-sector-claims-payment-software-solutions" => "pages#public_sector", :as => :public_sector
  match "private-sector-claims-payment-software-solutions" => "pages#private_sector", :as => :private_sector
  match "property-and-casualty" => "pages#property_casualty", :as => :property_casualty
  match "health-care-search-results" => 'search#index', :as => :search
  match "healthcare-insight-sitemap" => 'sitemap#sitemap', :as => :sitemap

  match "employee_login" => "employee_sessions#new", :as => :employee_login
  match "employee_logout" => "employee_sessions#destroy", :as => :employee_logout
  match "about-healthcare-insight" => "pages#about", :as => :about
  
  # Insight U Routes
  match "insight-university" => "university#index", :as => :university
  match "insight-university" => "university#iu_services", :as => :iuservices
  match "insight-university-resources" => "university#iu_resources", :as => :iuresources
  match "insight-university-login" => "student_sessions#new", :as => :student_login
  match "insight-university-logout" => "student_sessions#destroy", :as => :student_logout
  
  # Landing Page Returns
  match "claim-saver-webinar-thank-you" => "landing_pages#claim_saver_thank_you", :as => :claim_saver_thank_you
  
  # Redirect Paths
  match "PCI.html" => "pages#PCI", :as => :pci
  match "FCI.html" => "pages#FCI", :as => :fci
  match "DCI.html" => "pages#DCI", :as => :dci
  match "OCI.html" => "pages#OCI", :as => :oci
  match "PublicSector.html" => "pages#public_sector", :as => :pubsec
  match "PrivateSector.html" => "pages#private_sector", :as => :prisec
  match "PandC.html" => "pages#property_casualty", :as => :pncsec
  match "AboutUs.html" => "pages#about", :as => :oldabout
  match "Careers.html" => "pages#careers", :as => :oldcareers
  match "Services.html" => "pages#services", :as => :oldservices
  
  # Ajax Routes
  
  resources :quotes  
  resources :friend_invites
  resources :tutorial_videos
  resources :students
  resources :student_sessions
  resources :advertisements
  resources :goal_types
  resources :claim_types
  resources :business_type
  resources :service_inquiries
  resources :videos
  resources :free_trials
  resources :benefits
  resources :newsletter_subscriptions
  resources :tickets, :has_many => :ticket_assets
  resources :ticket_updates
  resources :ticket_statuses
  resources :priorities
  resources :departments
  resources :roles
  resources :employees
  resources :employee_sessions
  resources :document_types
  resources :coverflows
  resources :documents, :has_many => :assets
  resources :links, :has_many => :assets
  resources :article_types
  resources :articles, :has_many => :assets
  resources :events, :has_many => :assets
  resources :services, :has_many => :assets
  resources :users
  resources :user_sessions
  resources :uni_resources
  resources :banners
  resources :claim_savers
  
  # Default Path
  root :to => "payment_accuracy#home"

end

app/models/video.rb
# == Schema Information
#
# Table name: videos
#
#  id                       :integer(4)      not null, primary key
#  title                    :string(255)
#  description              :text
#  permalink                :string(255)
#  video_type_id            :integer(4)
#  third_party              :boolean(1)
#  third_party_url          :string(255)
#  created_at               :datetime
#  updated_at               :datetime
#  video_file_name          :string(255)
#  video_content_type       :string(255)
#  video_file_size          :integer(4)
#  video_updated_at         :datetime
#  video_thumb_file_name    :string(255)
#  video_thumb_content_type :string(255)
#  video_thumb_file_size    :integer(4)
#  video_thumb_updated_at   :datetime
#

class Video < ActiveRecord::Base
   
   belongs_to :video_type

   # Thinking Sphinx Indexes
   define_index do
     indexes description
     indexes title
   end

   # RedCloth (textilize)
   # acts_as_textiled  :description

   # Validations
   validates_presence_of :title, :description, :permalink

   # PaperClip
   has_attached_file :video,
                     :url => "/videos/:id/:style/:basename.:extension",
                     :path => ":rails_root/public/videos/:id/:style/:basename.:extension"
                     
   has_attached_file :video_thumb,
                     :styles => { :full => "512x288>", :small => "283x159>", :thumb => "128x72>" },
                     :url => "/video_thumbs/:id/:style/:basename.:extension",
                     :path => ":rails_root/public/video_thumbs/:id/:style/:basename.:extension"
                     
   # # Paperclip Validations
   # validates_attachment_presence :video
   # validates_attachment_content_type :video, :content_type => ['video/x-msvideo','video/avi','video/quicktime','video/3gpp','video/x-ms-wmv','video/mp4','video/mpeg']
   # 
   # # Attrs
   # attr_protected :video_file_name, :video_content_type, :video_file_size
   
   # Scopes
   scope :type, lambda { |typea| where('video_types.video_type = ?', typea).includes(:video_type)}
   scope :filtered_type, lambda { |typea| where('video_types.video_type != ?', typea).order("videos.created_at DESC").includes(:video_type) }
   scope :last_created, order("videos.created_at DESC")

   #============================= Class Methods ==================================#

   # Sets Permalink Routes
   def to_param
     "#{id}-#{permalink}"
   end
   
   def self.list(count, page)
     paginate(:per_page => count, :page => page, :order => "created_at DESC")
   end
  
end

app/models/video_type.rb
# == Schema Information
#
# Table name: video_types
#
#  id         :integer(4)      not null, primary key
#  video_type :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class VideoType < ActiveRecord::Base
  
  has_many :videos
  
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  
  before_filter :require_user, :except => [:index, :show]
  
  # GET /videos
  # GET /videos.xml
  def index
    @videos = Video.list(5, params[:page])
    @press_releases = Article.type('press_release').limit(5)
    @events = Event.upcoming_events.limit(1).last_created
    @advertisements = Advertisement.current_list.limit(2).order_list
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @videos }
    end
  end

  # GET /videos/1
  # GET /videos/1.xml
  def show
    @video = Video.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @video }
    end
  end

  # GET /videos/new
  # GET /videos/new.xml
  def new
    @video = Video.new

    respond_to do |format|
      format.html { render :layout => "admin" }
      format.xml  { render :xml => @video }
    end
  end

  # GET /videos/1/edit
  def edit
    @video = Video.find(params[:id])
    
    respond_to do |format|
      format.html { render :layout => "admin" }
    end
  end

  # POST /videos
  # POST /videos.xml
  def create
    @video = Video.new(params[:video])

    respond_to do |format|
      if @video.save
        flash[:notice] = 'Video was successfully created.'
        format.html { redirect_to(@video) }
        format.xml  { render :xml => @video, :status => :created, :location => @video }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @video.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /videos/1
  # PUT /videos/1.xml
  def update
    @video = Video.find(params[:id])

    respond_to do |format|
      if @video.update_attributes(params[:video])
        flash[:notice] = 'Video was successfully updated.'
        format.html { redirect_to(@video) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @video.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /videos/1
  # DELETE /videos/1.xml
  def destroy
    @video = Video.find(params[:id])
    @video.destroy

    respond_to do |format|
      format.html { redirect_to(videos_url) }
      format.xml  { head :ok }
    end
  end
end

app/views/videos/_banner.html.erb
<div id="inner_banner_short" class="grid_12 alpha omega">
  <div id="banner1">
    <%= image_tag "banners/inner_banners/video_banner.png", :alt => "HealthCare Insight Videos " %>
  </div>
  <%= render :partial => "layouts/cta_bar" %>
</div>

app/views/videos/_form.html.erb
<%= form_for(@video, :html => {:multipart => true}) do |f| %>
  <%= render :partial => "shared/error_block", :locals => {:object => @video} %>
  <p>
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :description %><br />
    <%= f.text_area :description, :cols => 28, :rows => 5 %>
  </p>
  <p>
    <%= f.label :permalink %><br />
    <%= f.text_field :permalink %>
  </p>
  <p>
    <%= f.label :video_type_id, "Video Type" %><br />
    <%= collection_select(:video, :video_type_id, VideoType.all, :id, :video_type) %>
  </p>
  <p>
    <%= f.label :video, "Video File (flv or f4v)" %><br />
    <%= f.file_field :video %>
  </p>
  <p>
    <%= f.label :video_thumb, "Video Thumbnail (512x288)" %><br />
    <%= f.file_field :video_thumb %>
  </p>
  <p>
    <%= f.label :third_party, "Third Party Video?" %><br />
    <%= f.check_box :third_party %>
  </p>
  <p>
    <%= f.label :third_party_url, "Third Party Link" %><br />
    <%= f.text_field :third_party_url %>
  </p>
  <p class="top_20_wrap">
    <%= f.submit 'Submit' %>
    <%= link_to 'Back', videos_path %>
  </p>
<% end %>

app/views/videos/edit.html.erb
<div class="grid_12 alpha omega full_wrap">
  <h1>Edit Video</h1>
  <%= render :partial => 'form' %>
</div>

app/views/videos/index.html.erb
<% page_title "Health Care Fraud Videos "%>
<% meta_keywords("health care fraud prevention videos, health care fraud videos, fraud awareness videos")%>
<% meta_description("Health Care fraud is a huge problem in America. HealthCare Insight provides videos to keep you informed and educated about the growing problem") %>

<% content_for :banner do %>
  <%= render :partial => 'shared/banners/short_banner', :locals => {:page => "videos"} %>
<% end %>

<div class="full_row">
  <div class="listed_items">
    <h2 class="green">Fraud Videos</h2>
    <%= render :partial => "shared/videos/video_list", :locals => {:videos => @videos} %>
  </div>
  <aside>
    <%= render :partial => 'shared/sidebar/press_releases', :locals => {:objects => @press_releases} %>
    <%= render :partial => 'shared/sidebar/events_list', :locals => {:objects => @events} %>
    <%= render :partial => 'shared/sidebar/current_ad', :locals => {:ads => @advertisements} %>
  </aside>
</div>

<% content_for :overlays do %>
  <div id="video_div" class="overlay">
    <div class="close"></div>
    <div id="player"></div>
  </div>
<% end %>

<% content_for :javascripts do %>
  <script type="text/javascript" charset="utf-8">
    $(document).ready(function() {
      app.ctaArrows();
      videos.indexBannerVideos();
    });
  </script>
<% end %>

app/views/videos/new.html.erb
<div class="grid_12 alpha omega full_wrap">
  <h2>Add A Video</h2>
  <%= render :partial => 'form' %>
</div>

app/views/videos/show.html.erb
<div class="grid_12 alpha omega full_wrap">
<p>
  <b>Title:</b>
  <%=h @video.title %>
</p>

<p>
  <b>Description:</b>
  <%=h @video.description %>
</p>

<p>
  <b>Video type:</b>
  <%=h @video.video_type_id %>
</p>

<p>
  <b>Third party:</b>
  <%=h @video.third_party %>
</p>

<p>
  <b>Third party url:</b>
  <%=h @video.third_party_url %>
</p>


<%= link_to 'Edit', edit_video_path(@video) %> |
<%= link_to 'Back', videos_path %>
</div>