config/routes.rb
Hci3::Application.routes.draw do
  
  # Verisk Pages
  match 'payment_accuracy' => 'payment_accuracy#home', :as => :home
  match 'claims_editing' => 'payment_accuracy#claim_editing', :as => :claim_editing
  match 'fraud_prevention' => 'payment_accuracy#fraud_prevention', :as => :fraud_prevention
  match 'bill_review' => 'payment_accuracy#bill_review', :as => :bill_review
  match 'about_us' => 'payment_accuracy#about_us', :as => :about_us
  match 'nucleus' => 'payment_accuracy#nucleus', :as => :nucleus
  match 'more_info' => 'payment_accuracy#more_info', :as => :more_info

  # Mail Route Paths
  match 'contacts_mailer' => "contacts#contacts_mailer", :as => :contact_mailer
  
  # Admin Paths
  match "login" => "user_sessions#new", :as => :login
  match "logout" => "user_sessions#destroy", :as => :logout
  match "hci-services" => "users#admin_services", :as => :admin_services
  match "hci-articles" => "users#admin_articles", :as => :admin_articles
  match "hci-events" => "users#admin_events", :as => :admin_events
  match "hci-videos" => "users#admin_videos", :as => :admin_videos
  match "hci-tutorial-videos" => "users#admin_tutorial_videos", :as => :admin_tutorial_videos
  match "hci-documents" => "users#admin_documents", :as => :admin_documents
  match "hci-banners" => "users#admin_banners", :as => :admin_banners
  match "hci-advertisements" => "users#admin_ads", :as => :admin_ads
  match "hci-quotes" => "users#admin_quotes", :as => :admin_quotes
  
  # Custom Named Routes
  match "invite-a-friend" => "landing_pages#invite_friend", :as => :invite_friend
  match "thank-you-for-inviting-a-friend" => "landing_pages#invite_thank_you", :as => :invite_thank_you
  match "upload-issuu" => "issuu_uploads#index", :as => :issuu_upload
  match "healthcare-insight-document" => 'issuu_uploads#show', :as => :issue
  # match "nucleus" => "pages#nucleus", :as => :nucleus
  match "healthcare-insight-markets" => "pages#markets", :as => :markets
  match "healthcare-insight-resources" => "pages#resources", :as => :res
  match "healthcare-insight-press-kit" => "pages#press_kit", :as => :press_kit
  match "contact-healthcare-insight" => "contacts#contact_us", :as => :contact
  match "thank-you" => "contacts#thank_you", :as => :contact_thank_you
  match "health-care-press" => "announcements#index", :as => :press
  match "health-care-resources" => "resources#index", :as => :media
  match "careers" => "pages#careers", :as => :careers
  match "healthcare-insight-partners" => "pages#partner", :as => :partners
  match "healthcare-insight-accreditations" => "pages#accreditations", :as => :accreditations
  match "healthcare-insight-privacy-policy-and-disclaimers" => "pages#privacy_policy", :as => :privacy
  match "healthcare-insight-social-media-links" => "pages#social_media", :as => :social
  match "public-sector-claims-payment-software-solutions" => "pages#public_sector", :as => :public_sector
  match "private-sector-claims-payment-software-solutions" => "pages#private_sector", :as => :private_sector
  match "property-and-casualty" => "pages#property_casualty", :as => :property_casualty
  match "health-care-search-results" => 'search#index', :as => :search
  match "healthcare-insight-sitemap" => 'sitemap#sitemap', :as => :sitemap

  match "employee_login" => "employee_sessions#new", :as => :employee_login
  match "employee_logout" => "employee_sessions#destroy", :as => :employee_logout
  match "about-healthcare-insight" => "pages#about", :as => :about
  
  # Insight U Routes
  match "insight-university" => "university#index", :as => :university
  match "insight-university" => "university#iu_services", :as => :iuservices
  match "insight-university-resources" => "university#iu_resources", :as => :iuresources
  match "insight-university-login" => "student_sessions#new", :as => :student_login
  match "insight-university-logout" => "student_sessions#destroy", :as => :student_logout
  
  # Landing Page Returns
  match "claim-saver-webinar-thank-you" => "landing_pages#claim_saver_thank_you", :as => :claim_saver_thank_you
  
  # Redirect Paths
  match "PCI.html" => "pages#PCI", :as => :pci
  match "FCI.html" => "pages#FCI", :as => :fci
  match "DCI.html" => "pages#DCI", :as => :dci
  match "OCI.html" => "pages#OCI", :as => :oci
  match "PublicSector.html" => "pages#public_sector", :as => :pubsec
  match "PrivateSector.html" => "pages#private_sector", :as => :prisec
  match "PandC.html" => "pages#property_casualty", :as => :pncsec
  match "AboutUs.html" => "pages#about", :as => :oldabout
  match "Careers.html" => "pages#careers", :as => :oldcareers
  match "Services.html" => "pages#services", :as => :oldservices
  
  # Ajax Routes
  
  resources :quotes  
  resources :friend_invites
  resources :tutorial_videos
  resources :students
  resources :student_sessions
  resources :advertisements
  resources :goal_types
  resources :claim_types
  resources :business_type
  resources :service_inquiries
  resources :videos
  resources :free_trials
  resources :benefits
  resources :newsletter_subscriptions
  resources :tickets, :has_many => :ticket_assets
  resources :ticket_updates
  resources :ticket_statuses
  resources :priorities
  resources :departments
  resources :roles
  resources :employees
  resources :employee_sessions
  resources :document_types
  resources :coverflows
  resources :documents, :has_many => :assets
  resources :links, :has_many => :assets
  resources :article_types
  resources :articles, :has_many => :assets
  resources :events, :has_many => :assets
  resources :services, :has_many => :assets
  resources :users
  resources :user_sessions
  resources :uni_resources
  resources :banners
  resources :claim_savers
  
  # Default Path
  root :to => "payment_accuracy#home"

end

app/models/document.rb
# == Schema Information
#
# Table name: documents
#
#  id                   :integer(4)      not null, primary key
#  title                :string(255)
#  description          :text
#  document_type_id     :integer(4)
#  download_link        :string(255)
#  issuu_url            :string(255)
#  meta_description     :text
#  keywords             :string(255)
#  permalink            :string(255)
#  created_at           :datetime
#  updated_at           :datetime
#  brochure             :boolean(1)
#  brochure_order       :integer(4)
#  service_id           :integer(4)
#  brochure_sub_heading :text
#

class Document < ActiveRecord::Base
  
  belongs_to :document_type
  belongs_to :service
  
  has_many :assets, :as => :attachable
  accepts_nested_attributes_for :assets, :allow_destroy => true
  has_many :coverflows, :as => :cflow, :class_name => "Coverflow"
  accepts_nested_attributes_for :coverflows, :allow_destroy => true
  
  # Validations
  validates_presence_of :title, :description, :permalink
  validates_numericality_of :brochure_order, :on => :create, :message => "is not a number"
  
  # Thinking Sphinx Indexes
  define_index do
    indexes description
    indexes title
  end
  
  # RedCloth (textilize)
  # acts_as_textiled  :description
  
  # Named Scopes
  scope :last_created, order("created_at DESC")
  scope :brochures, where("brochure = ?", true).order("brochure_order ASC").includes(:coverflows)
  
  #============================= Class Methods ==================================#
  
  # Sets Permalink Routes
  def to_param
    "#{id}-#{permalink}"
  end
  
  #pulls the assets from the form
  # def attachments=(attachments)
  #   attachments.each do |attachment|
  #     assets.build(attachment)
  #   end
  # end
  
end

app/models/document_type.rb
# == Schema Information
#
# Table name: document_types
#
#  id                 :integer(4)      not null, primary key
#  document_type      :string(255)
#  created_at         :datetime
#  updated_at         :datetime
#  document_extension :string(255)
#

class DocumentType < ActiveRecord::Base
  
  has_many :documents
  
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  
  before_filter :require_user, :except => [:show]
  
  # GET /documents
  # GET /documents.xml
  def index
    @documents = Document.all
    respond_to do |format|
      format.html # index.html.erb
      format.xml # index.xml.builder
    end
  end

  # GET /documents/1
  # GET /documents/1.xml
  def show
    @banner_size = 'large'
    @document = Document.find(params[:id])
    @documents = Document.brochures
    respond_to do |format|
      format.html # { render :layout => "issuu"}
      format.xml  { render :xml => @document }
    end
  end

  # GET /documents/new
  # GET /documents/new.xml
  def new
    @document = Document.new
    @document_types = DocumentType.all
    @document.assets.build
    @document.coverflows.build
    respond_to do |format|
      format.html { render :layout => "admin"}
      format.xml  { render :xml => @document }
    end
  end

  # GET /documents/1/edit
  def edit
    @document = Document.find(params[:id])
    @document_types = DocumentType.all
    if @document.assets.blank?
      @document.assets.build
    end
    if @document.coverflows.blank?
      @document.coverflows.build
    end
    respond_to do |format|
      format.html { render :layout => "admin"}
    end
  end

  # POST /documents
  # POST /documents.xml
  def create
    @document = Document.new(params[:document])
    @document_types = DocumentType.all
    respond_to do |format|
      if @document.save
        flash[:notice] = 'Document was successfully created.'
        format.html { redirect_to(@document) }
        format.xml  { render :xml => @document, :status => :created, :location => @document }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @document.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /documents/1
  # PUT /documents/1.xml
  def update
    @document = Document.find(params[:id])

    respond_to do |format|
      if @document.update_attributes(params[:document])
        flash[:notice] = 'Document was successfully updated.'
        format.html { redirect_to(@document) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @document.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /documents/1
  # DELETE /documents/1.xml
  def destroy
    @document = Document.find(params[:id])
    @document.destroy

    respond_to do |format|
      format.html { redirect_to(documents_url) }
      format.xml  { head :ok }
    end
  end
end

app/views/documents/_banner.html.erb
<div class="services_inner_banner inner_banner">
  
</div>

app/views/documents/_document.html.erb
<div class="nucleus_banner">
  <% if document.issuu_url? %>
  <div id="issuu_frame">
   <iframe src="<%= document.issuu_url %>"></iframe>
  </div>
  <% end %>
</div>
<div class="full_row">
  <%= render :partial => 'shared/resources/resource_brochures', :locals => {:documents => documents} %>
</div>

app/views/documents/_form.html.erb
<%= form_for(@document, :html => {:multipart => true }) do |f| %>
  <%= render :partial => "shared/error_block", :locals => {:object => @document} %>

<div class="grid_5">
  <h3>Document Content</h3>
  <p>
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :description %><br />
    <%= f.text_area :description, :rows => 5, :cols => 28 %>
  </p>
  <p>
    <%= f.label "Select Document Type" %><br />
    <%= collection_select(:document, :document_type_id, @document_types, :id, :document_type) %>
  </p>
  <p>
    <%= f.label :issuu_url %><br />
    <%= f.text_field :issuu_url %>
  </p>
  <p>
    <%= f.label :download_link, "Pardot Download Link" %><br />
    <%= f.text_field :download_link %>
  </p>
  <p>
    <% for asset in @document.assets %>
    <%= fields_for "document[attachments][]", asset do |asset_form|%>
    <%= asset_form.label "Upload Documents" %><br />
    <%= asset_form.file_field :attachment, :size => 16 %>
    <% end %>
    <% end %>
  </p>
  <p>
    <%= f.fields_for :coverflows do |cover_form|%>
    <%= cover_form.label "Add Cover Flow" %><br />
    <%= cover_form.file_field :cover, :size => 16 %>
    <% end %>
  </p>
  <p>
    <%= f.check_box :brochure %>
    <%= f.label :brochure, "Is Brochure?" %>
  </p>
  <p>
    <%= f.label :brochure_order %><br />
    <%= f.text_field :brochure_order %>
  </p>
  <p>
    <%= f.label :brochure_sub_heading, "Sub Heading" %><br />
    <%= f.text_area :brochure_sub_heading, :rows => 5, :cols => 28 %>
  </p>
  <p>
    <%= f.label "Service for Brochure" %><br />
    <%= collection_select(:document, :service_id, Service.all, :id, :title) %>
  </p>
</div>
<div class="grid_5">
  <h3>Document SEO</h3>
  <p>
    <%= f.label :meta_description %><br />
    <%= f.text_area :meta_description, :rows => 5, :cols => 28 %>
  </p>
  <p>
    <%= f.label :keywords %><br />
    <%= f.text_field :keywords %>
  </p>
  <p>
    <%= f.label :permalink %><br />
    <%= f.text_field :permalink %>
  </p>
</div>
<div class="grid_5">
  <h3>Document Dependencies</h3>
  <p>
    <%= link_to "Create New Doc Type", new_document_type_path %>
  </p>
  <p>
    <h4>Document Types Available</h4>
    <ul>
      <% for document_type in @document_types %>
      <li><%= document_type.document_type %> | Ext: <%= document_type.document_extension %></li>
      <% end %>
    </ul>
  </p>
</div>
<div class="clear"></div>
<div class="grid_5"
  <p>
    <%= f.submit 'Submit' %>
    <%= link_to "Back", request.env["HTTP_REFERER"]%>
  </p>
</div>
<% end %>

app/views/documents/_index_document.html.erb
<% documents.each do |doc| %>
  <div class="index_listing">
    <% doc.coverflows.each do |coverflow| %>
      <%= link_to image_tag(coverflow.cover.url(:brochure), :alt => doc.title), document_path(doc), :class => "index_listing_image" %>
    <% end %>
    <h3><%= link_to "#{doc.title}", document_path(doc)  %> | <%= link_to "Download", " #{doc.download_link}", :alt => "Download #{doc.title} Brochure" %></h3>
    <p>
      <%= doc.brochure_sub_heading %>
    </p>
    <div class="clear"></div>
  </div>
<% end %>

app/views/documents/edit.html.erb
<h2 class="full_wrap">Editing <%= @document.title if @document %></h2>
<%= render :partial => "form", :locals => {:document => @document, :document_types => @document_types} %>

app/views/documents/index.html.erb
<% page_title "Health Care Documents"%>

<%= render :partial => "index_document", :locals => {:documents => @documents}%>
<div class="space_left">
  <%= link_to "Back", request.env["HTTP_REFERER"], :class => "btn"%>
</div>

app/views/documents/new.html.erb
<h2 class="full_wrap">Upload A New Document</h2>
<%= render :partial => "form", :locals => {:document => @document, :document_types => @document_types} %>

app/views/documents/show.html.erb
<% if @document.keywords
  meta_keywords(@document.keywords)
  end %>
<% if @document.meta_description
  meta_description(@document.meta_description)
  end %>
<% page_title "#{@document.title} " %>

<% if @document.issuu_url? %>
  <% content_for :banner do %>
    <div id="issuu_frame">
      <iframe src="<%= @document.issuu_url %>"></iframe>
    </div>
  <% end %>
<% end %>

<div class="full_row">
  <%= render :partial => 'shared/resources/resource_brochures', :locals => {:documents => @documents} %>
</div>